import { useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { GiftVoucher, CreateVoucherForm } from '@/types/voucher';
import { addYears } from 'date-fns';

export const useVouchers = () => {
  const [vouchers, setVouchers] = useState<GiftVoucher[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchUserVouchers = async () => {
    setLoading(true);
    setError(null);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Nem vagy bejelentkezve');

      const { data, error: fetchError } = await supabase
        .from('gift_vouchers')
        .select(`
          *,
          flight_package:flight_packages(id, name, short_description, duration_minutes, base_price_huf)
        `)
        .eq('purchaser_user_id', user.id)
        .order('created_at', { ascending: false });

      if (fetchError) throw fetchError;
      setVouchers(data as GiftVoucher[] || []);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Hiba az utalványok betöltésekor');
    } finally {
      setLoading(false);
    }
  };

  const createVoucher = async (form: CreateVoucherForm, operatorId: string, price: number) => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) throw new Error('Nem vagy bejelentkezve');

    const { data, error } = await supabase
      .from('gift_vouchers')
      .insert([{
        operator_id: operatorId,
        purchaser_user_id: user.id,
        flight_package_id: form.flight_package_id,
        recipient_name: form.recipient_name,
        recipient_email: form.recipient_email || null,
        personal_message: form.personal_message || null,
        purchase_price_huf: price,
        expires_at: addYears(new Date(), 1).toISOString(),
        voucher_code: '', // Generated by database function
      }])
      .select(`
        *,
        flight_package:flight_packages(id, name, short_description, duration_minutes, base_price_huf)
      `)
      .single();

    if (error) throw error;
    return data as GiftVoucher;
  };

  const validateVoucherCode = async (code: string) => {
    const { data, error } = await supabase
      .from('gift_vouchers')
      .select(`
        *,
        flight_package:flight_packages(id, name, base_price_huf)
      `)
      .eq('voucher_code', code.toUpperCase())
      .eq('status', 'active')
      .single();

    if (error || !data) {
      return null;
    }

    // Check if expired
    if (new Date(data.expires_at) < new Date()) {
      return null;
    }

    return data as GiftVoucher;
  };

  const redeemVoucher = async (voucherId: string, bookingId: string) => {
    const { error } = await supabase
      .from('gift_vouchers')
      .update({
        status: 'redeemed',
        redeemed_at: new Date().toISOString(),
        redeemed_booking_id: bookingId,
      })
      .eq('id', voucherId);

    if (error) throw error;
  };

  return {
    vouchers,
    loading,
    error,
    fetchUserVouchers,
    createVoucher,
    validateVoucherCode,
    redeemVoucher,
  };
};
